# Generated by Django 5.0.2 on 2024-03-01 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0002_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentOnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPI.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='available_products',
            field=models.ManyToManyField(related_name='students', through='myAPI.StudentOnProduct', to='myAPI.product'),
        ),
    ]
