# Generated by Django 5.0.2 on 2024-03-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0003_student_studentonproduct_student_available_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='myAPI.product')),
                ('students', models.ManyToManyField(related_name='groups', to='myAPI.student')),
            ],
        ),
    ]
